force-app/main/default/objects/Account/fields/Total_Licenses__c.field-meta.xml
<CustomField>
    <fullName>Total_Licenses__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total number of licenses</description>
    <label>Total Licenses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Instance__c/Instance__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Instance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Instances</relationshipLabel>
    <relationshipName>Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Instance__c/fields/Licenses__c.field-meta.xml
<CustomField>
    <fullName>Licenses__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Licenses</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Instance__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Trial Instance&apos;</defaultValue>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial Instance</fullName>
            </value>
            <value>
                <fullName>Standard Instance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InstanceTriggerHandlerHelper.cls
 /**
    @author Yan Kuhalski
    @description class that includes all logic that is called from InstanceTriggerHandler to handle changes of Instances
*/
public with sharing class InstanceTriggerHandlerHelper {
    private static final String STANDART_TYPE_NAME = 'Standard Instance';
    private static final String TRAIL_TYPE_NAME = 'Trial Instance';

    /**
        @description Find new or deleted instances owners and set new licenses total amount value
        @param  List<Instance__c> of new or deleted instances
        @return List<Instance__c> of accounts with changed licenses total amount value
    */
    public static List<Account> recalculateOwnerLicensesAmount(List<Instance__c> instances) {
        List<Instance__c> standartInstances = new List<Instance__c>();
        List<Id> standartOwnersId = new List<Id>();

        for (Instance__c newInstance : instances) {
            if(newInstance.Type__c == STANDART_TYPE_NAME) {
                standartInstances.add(newInstance);
                standartOwnersId.add(newInstance.Account__c);
            }
        }

        Map<Id, Account> instancesOwners = new Map<Id, Account> ([
            SELECT Total_Licenses__c
            FROM Account
            WHERE Id IN : standartOwnersId
        ]);

        Boolean isInsertTrigger = Trigger.isExecuting && Trigger.isInsert;
        Boolean isDeleteTrigger = Trigger.isExecuting && Trigger.isDelete;

        for (Instance__c standartInstance : standartInstances) {
            if (isInsertTrigger) {
                instancesOwners.get(standartInstance.Account__c).Total_Licenses__c += standartInstance.Licenses__c;
            }
            if (isDeleteTrigger) {
                instancesOwners.get(standartInstance.Account__c).Total_Licenses__c -= standartInstance.Licenses__c;
            }
        }

        return instancesOwners.values();
    }

    /**
        @description Find updated instances owners and set new licenses total amount value
        @param  Map<Id,Instance__c> map of old instances
                List<Instance__c> list of updated instances
        @return List of accounts with changed licenses total amount value
    */
    public static List<Account> recalculateOwnerLicensesAmount(Map<Id,Instance__c> oldInstances, List<Instance__c> newInstances) {
        List<Id> accountToUpdateIds = new List<Id>();
        List<Instance__c> instancesWithNewType = new List<Instance__c>();
        List<Instance__c> instancesWithNewLicensesValue = new List<Instance__c>();
        
        for (Instance__c newInstance : newInstances) {
            Instance__c oldInstance = oldInstances.get(newInstance.Id);
            if (oldInstance.Type__c == TRAIL_TYPE_NAME && newInstance.Type__c == STANDART_TYPE_NAME) {
                accountToUpdateIds.add(newInstance.Account__c);
                instancesWithNewType.add(newInstance);
            } else if (oldInstance.Licenses__c != newInstance.Licenses__c) {
                accountToUpdateIds.add(newInstance.Account__c);
                instancesWithNewLicensesValue.add(newInstance);
            }
        }
        
        Map<Id, Account> instancesOwners = new Map<Id, Account> ([
            SELECT Total_Licenses__c
            FROM Account
            WHERE Id IN : accountToUpdateIds
        ]);
        
        for (Instance__c instanceWithNewType : instancesWithNewType) {
            instancesOwners.get(instanceWithNewType.Account__c).Total_Licenses__c += instanceWithNewType.Licenses__c;
        }

        for (Instance__c instanceWithNewLicensesValue : instancesWithNewLicensesValue) {
            instancesOwners.get(instanceWithNewLicensesValue.Account__c).Total_Licenses__c += 
            (instanceWithNewLicensesValue.Licenses__c - oldInstances.get(instanceWithNewLicensesValue.Id).Licenses__c);
        }

        return instancesOwners.values();
    }
}